defaults:
  - train
  - _self_
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: grid

hydra:
  mode: MULTIRUN
  output_subdir: hydra
  sweeper:
   direction: minimize
   study_name: hspn
   storage: null
   n_trials: 10
   n_jobs: 1
   params:
     optimizer_factory._target_: choice(torch.optim.SGD ,torch.optim.Adam)
     optimizer_factory.lr: range(0.0001, 0.0005, step=0.0001)

