log_level: INFO
log_dir: logs
output_dir: output
random_seed: 42

data:
  train_path: data/train.npz
  val_path: null  # If null, will create validation split from training data
  test_path: null
  val_split: 0.2  # Fraction of training data to use for validation if val_path is null

model:
  latent_dim: 20
  einsum: "ij,ik->ik"
  random_seed: 42

  branch:
    width: 64
    depth: 3
    activation: relu
    structure_file: null  # A maybe path to JSON network file

  trunk:
    width: 64
    depth: 3
    activation: relu
    structure_file: null  # A maybe path to JSON network file

training:
  epochs: 100
  batch_size: 32
  learning_rate: 0.001
  optimizer: adam

  # TODO: Learning rate schedule
  lr_schedule:
    enabled: false
    decay_rate: 0.1
    decay_steps: 20

  # Early stopping
  patience: 10
  min_delta: 0.0001

  # Checkpointing
  checkpoint_dir: checkpoints
  save_interval: 10

  # Hardware opts
  distributed: false
  mixed_precision: false
  xla_compilation: false